name: CI

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    name: Update package versions
    runs-on: ubuntu-latest
    permissions:
      # Required to push updated spec files to this repo
      contents: write

    steps:
      - uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          sudo apt-get install -y jq

      - name: Setup git credentials
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
      - name: Update package version
        run: |
          ./update-spec.sh specs/mpvacious.spec
